### ISSUE TITLE
MPICH option to building container

### ISSUE THREAD

**Issue by jdha** [NOC-MSM/CoNES#10]
Add and test option to build and run MPICH version of the def file. 

Use NEMO_in to determine the MPI required?

**Comment by jdha** [comment]
Again - open a separate PR and merge when ready

**Comment by wood-chris** [comment]
@jdha latest commit should fix this, I hope!

**Comment by jdha** [comment]
By opening a PR then it'll kick off the test build - which in this case is probably a good thing as we'll see if the build works.  The fact we have two MPI options the test build should really include both - it makes it a lengthy process (but probably necessary - just to check the container will build with both after any new commits). OK - I think in order to clean things up, if you submit a PR for the MPICH branch we can test the build, if that works I'll merge with the initial code branch and then back into 'main' - that way we'll have a release 0.0.1 (which by default will be MPICH) - this will allow you to play with it on ARCHER2 and set up a runscript. In the meantime I'll have a go at modifying the test and build YAML files to only test prior to a push to main and also to produce both a MPICH and openMPI release. How does that sound?

**Comment by wood-chris** [comment]
I'll have to rearrange folders a bit if we think we need the ability to have both MPICH and OpenMPI installed in the same container
