### ISSUE TITLE
Comms library

### ISSUE THREAD

**Issue by wood-chris** [NOC-MSM/CoNES#24]
Currently in the container I install `libfabric` with MPICH, but AndrewC has found that UCX is better. I'll update to this and see if performance is better

**Comment by wood-chris** [comment]
Actually, my understanding was wrong.

libfabric is the underlying library, with _either_ ofi or ucx between it and MPI. ARCHER2 uses ofi by default, we should make sure we compile mpi with ucx in the container

**Comment by jdha** [comment]
both compile options are now available
