### ISSUE TITLE
Tidy Container (does this lead to better performance?)

### ISSUE THREAD

**Issue by jdha** [NOC-MSM/CoNES#9]
Open a PR to examine whether optimising the container in terms of size improves performance.

I guess this question could also be addressed by reducing the number of containers on each node - but it would be preferable not to do this for cost reasons.

**Comment by wood-chris** [comment]
I've been looking at this today. Some thoughts:

I went through the linked libraries from everything installed in opt, and removed unused ones:

```
cd /opt/
find . ! \( -name 'libhdf5_hl.so.200' -o -name 'libhdf5.so.200' -o -name 'libmpi.so.12' -o -name 'libmpifort.so.12' -o -name 'libnetcdff.a' -o -name 'libnetcdf.a' -o -name 'libhdf5_hl.a' -o -name 'libhdf5.a' -o -name 'nemo' -o -name 'xios' \) -type f -delete
```

this reduced the size of the directory by more than 100 mb.

I also `apt remove`d several packages that won't be needed at runtime (the largest, `git`, being ~35 mb).

But - I've now realised that sif is a highly compressed format. Removing ~150 mb of unused packages actually only reduces the size of the resulting sif by ~30 mb

**Comment by wood-chris** [comment]
2nd thought: use a much more lean distro of linux, e.g. `alpine`. The challenge here would be that alpine uses a totally different package management system (`apk` rather than `apt`), which has a much smaller software repo. It's much more likely we'd need to build more from scratch

**Comment by wood-chris** [comment]
Alpine also uses musl, rather than glibc, making compiling things a little more tricky

**Comment by wood-chris** [comment]
Just as a quick test, I created three vanilla containers:

```
Bootstrap: library
From: alpine:3.9.2
```

 - resulting container 2.6 MB
 
```
Bootstrap: docker 
From: ubuntu
```

 - resulting container 27 MB
 
```
Bootstrap: library
From: ubuntu:20.04
```

 - resulting container 36 MB
 
 Given the size of all the libraries we're adding, I think trying to save 30 MB here is probably a bit fruitless (especially given the difficulties of `apk` vs `apt`).

**Comment by jdha** [comment]
_Bloating_ the container to >500MB doesn't appear to have an impact on performance. The only benefit to shrinking the size is for file transfers. I think we'll close this for now.
